---
title: "Visualize Nine Card Results"
author: "Bailey Joseph"
date: "6/28/2020"
output: html_document
---


```{r}
library(tidyverse)
library(glue)
library(plotly)
results <- read_csv("data/results.csv")
```

```{r}
theme_clean <- function() {
  theme_bw(base_size = 11) +
    theme(text = element_text(family = "Roboto"),
          panel.grid.major.x = element_blank(),
          panel.grid.minor.x = element_blank(),
          panel.grid.minor.y = element_blank(),
          panel.background = element_rect(colour = "#E1E1E1"),
          panel.border = element_blank())
}

```

```{r}
results %>% 
  filter(notes %in% c("Looking for best strategy against an opponent who knocks only at 0"),
         player_number == 1) %>% 
  mutate(knocked_at = as.numeric(substr(knock_strategy, 9, nchar(knock_strategy)))) %>% 
  select(knocked_at, everything()) %>% 
  #bind_rows(grid_search_half_triangle %>% filter(opp_knocked_at == 0))
  rename(`Average Win per Round` = avg_win) %>% 
  ggplot(aes(x = knocked_at, y = `Average Win per Round`)) +
    geom_point(size = 3, aes(color = `Average Win per Round`, text = glue("Knocked At: {knocked_at}\nOpponent: Knocks at 0\nTrials: {rounds}\nAverage Time per Round: {round(elapsed_seconds/rounds, 2)} Seconds\nAverage Win per Round: {round(`Average Win per Round`, 2)}\nRound level Variance: {round(var_win, 2)}\n"))) +
    geom_hline(yintercept = 0) +
    labs(title = "First Grid Search against Opponent who Knocks at 0",
         y = "Average win Per Round",
         x = "Constant Knock Strategy") +
    scale_color_gradient2(high = "dark green") +
    theme_clean()

ggplotly(tooltip = "text")
```


```{r}

constant_grid_data <- results %>% 
  filter(notes %in% c("Looking for best strategy against an opponent who knocks only at 0",
                      "Completing the grid search on constant knock strategies.")) %>% 
  mutate(knocked_at = as.numeric(substr(knock_strategy, 9, nchar(knock_strategy)))) %>% 
  select(knocked_at, everything()) 


grid_search_half_triangle <- constant_grid_data %>% 
  mutate(other_player = 1 - player_number) %>% 
  filter(player_number == 1) %>% 
  left_join(constant_grid_data %>% select(sim_id, opp_knocked_at = knocked_at, opp_wins = wins, player_number),
            by = c("other_player" = "player_number", "sim_id")) %>% 
  group_by(knocked_at, opp_knocked_at) %>% 
  # This only removes some rows for when knock strategies are the same, so there are two rows which average to 0
  summarize(avg_win = weighted.mean(avg_win, rounds),
            var_win = weighted.mean(var_win, rounds),
            rounds = sum(rounds),
            wins = sum(wins),
            opp_wins = sum(opp_wins),
            elapsed_seconds = sum(elapsed_seconds)
            ) %>% 
  ungroup() 

constant_conservative_knock_grid_search <- grid_search_half_triangle %>% 
  bind_rows(
    grid_search_half_triangle %>% 
      rename(opp_knocked_at = knocked_at,
             knocked_at = opp_knocked_at,
             opp_wins = wins,
             wins = opp_wins) %>% 
      mutate(avg_win = -avg_win)
  ) %>% 
  group_by(knocked_at, opp_knocked_at) %>% 
  slice(1) %>% 
  ungroup() %>% 
  mutate(avg_win = ifelse(knocked_at == opp_knocked_at, 0, round(avg_win, 2))) %>% 
  rename(`Average Win per Round` = avg_win) %>% 
  ggplot(aes(x = knocked_at, y = opp_knocked_at, fill = `Average Win per Round`)) +
  geom_tile(aes(text = glue("Knocked At: {knocked_at}\nOpponent Knocks At: {opp_knocked_at}\nTrials: {rounds}\nAverage Time per Round: {round(elapsed_seconds/rounds, 2)} Seconds\nAverage Win per Round: {round(`Average Win per Round`, 2)}\nNumber of Wins: {wins}\nRound level Variance: {round(var_win, 2)}\n"))) +
  geom_text(aes(label = `Average Win per Round`), size = 3, alpha = .5) +
  scale_fill_gradient2(high = "dark green") +
  theme_clean() +
  labs(title = "Grid Search on Conservative Constant Knock Strategies",
         x = "Knock Strategy",
         y = "Opponent Knock Strategy") 
# TODO: make it compare on hover by default.
ggplotly(constant_conservative_knock_grid_search, tooltip = "text")

ggsave("visuals/constant_conservative_knock_grid_search.png",
       constant_conservative_knock_grid_search,
       height = 5, width = 7, units = "in", dpi = 400)
```

# Run a simulation/tournament

```{r}
grid_search_full_frame <- grid_search_half_triangle %>% 
  bind_rows(
    grid_search_half_triangle %>% 
      rename(opp_knocked_at = knocked_at,
             knocked_at = opp_knocked_at,
             opp_wins = wins,
             wins = opp_wins) %>% 
      mutate(avg_win = -avg_win)
  ) %>% 
  group_by(knocked_at, opp_knocked_at) %>% 
  slice(1) %>% 
  ungroup()

run_tourney <- function(full_frame, rounds) {
  tourney_winnings <- vector("list", length = rounds)
  tourney_weights <- vector("list", length = rounds + 1)
  curr_weight_frame <- data.frame(knocked_at = seq(0, 60, 5),
                                  weight = 1)
  tourney_weights[[1]] <- curr_weight_frame %>% mutate(round = 0)
  for (i in 1:rounds) {
    round_results <- full_frame %>% 
      # Do not count games against same strategy since that's just noise
      filter(knocked_at != opp_knocked_at) %>% 
      left_join(curr_weight_frame, by = c("opp_knocked_at" = "knocked_at")) %>% 
      group_by(knocked_at) %>% 
      summarize(avg_win_tourney = weighted.mean(avg_win, weight)) %>% 
      ungroup() %>% 
      mutate(weight = (avg_win_tourney - min(avg_win_tourney))/(max(avg_win_tourney) - min(avg_win_tourney)))
    tourney_winnings[[i]] <- round_results %>% select(knocked_at, avg_win_tourney) %>% mutate(round = i)
    curr_weight_frame <- round_results %>% select(knocked_at, weight) %>% mutate(round = i)
    tourney_weights[[i + 1]] <- curr_weight_frame
  }
  tourney_winnings <- bind_rows(tourney_winnings)
  tourney_weights <- bind_rows(tourney_weights)
  return(list("winnings" = tourney_winnings, "weights" = tourney_weights))
}

tourney_results <- run_tourney(grid_search_full_frame, 10)

tourney_results$weights %>% 
  mutate(knocked_at = factor(knocked_at)) %>% 
  ggplot(aes(x = round, y = weight, color = knocked_at, group = knocked_at)) + geom_line()
ggplotly()

tourney_results$winnings %>% 
  mutate(knocked_at = factor(knocked_at)) %>% 
  ggplot(aes(x = round, y = avg_win_tourney, color = knocked_at, group = knocked_at)) + geom_line()
ggplotly()
```

